[package]
name = "firmware-rs"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Firmware for a smart coffee scale using an ESP32 and HX711"
rust-version = "1.86"

[[bin]]
name = "firmware-rs"
harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[dependencies]
anyhow = "1"
critical-section = "1"
embedded-graphics = "0.8"
esp-idf-svc = { version = "0.52" }
esp32-nimble = "0.12"
loadcell = "0.3"
log = { version = "0.4", default-features = false }
signalo_filters = "0.6.1"
ssd1306 = "0.10"

[build-dependencies]
embuild = "0.33.4"
