[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"


[env]
ESP_LOGLEVEL = "INFO"
[build]
rustflags = [
  "-C",
  "link-arg=-Tlinkall.x",
  "-C",
  "link-arg=-Trom_functions.x",
  "-C",
  "link-arg=-nostartfiles",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["core"]
